version: '3.3'

services:
  nginx:
    image: nginx:1.21.6-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./website:/website
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:8.1.2-fpm-alpine3.15
    restart: always
    volumes:
      - ./website:/website

